# CLI 语言 可选 zh-CN(中文) en(英文)
language: zh-CN
# 日志登记
log_level: info
# 调试模式 开 - true 关 - false
debug: true
# geo2ip 数据文件
geo2ip: /Users/yuantong/Documents/GeoIP2-City.mmdb
# 仅关注在线用户
follow_only_online_users: true
# 是否开启mongodb
use_mongo: true
# 是否分析TTL
use_ttl: true
# 是否分析user-agent
use_ua: true
# 是否分析应用特征
use_feature: true
# 捕获子命令相关配置
capture:
  # 离线数据包文件
  offline_file:
  # 网卡
  nic: en0
# web 前端页面相关配置
web:
  # 前端接口端口
  port: 8088
# 忽略域名特征
ignore_feature:
  - com.cn
  - weixin.qq
  - qq.com
  - baidu.com
# 权重
feature:
  sni:
    time_window: 60
    count_size: 10
# 移动设备握手特征
mobile_device_feature:
  huawei:
    domains:
      - "huawei.com"
      - "hicloud.com"
      - "myhuaweicloud.cn"
    icon: "icon-huawei"
  xiaomi:
    domains:
      - "xiaomi.com"
      - "miui.com"
    icon: "icon-xiaomi"
  oppo:
    domains:
      - "oppo.com"
    icon: "icon-oppo"
  vivo:
    domains:
      - "vivo.com"
    icon: "icon-vivo"
  samsung:
    domains:
      - "samsung.com"
    icon: "icon-samsung"
  apple:
    domains:
      - "apple.com"
      - "icloud.com.cn"
    icon: "icon-apple"
  meizu:
    domains:
      - "meizu.com"
    icon: "icon-meizu"
  honor:
    domains:
      - "honor.com"
    icon: "icon-rongyao"
  oneplus:
    domains:
      - "oneplus.com"
    icon: "icon-OP_LU_Reg_1L_RGB_red_copy-01"
  realme:
    domains:
      - "realme.com"
      - "realmeui.com"
    icon: "icon-zhenworealme_logo"
# mongodb，用于流分析持久化存储与查询
mongodb:
  host: 127.0.0.1
  port: 27017
redis:
  # dpi程序使用，主要用户存储 ip hash、observer（观察者）、应用流量统计
  dpi:
    host: 127.0.0.1
    port: 6379
    password: ""
  # 4k 在线表, 用于dpi同步在线用户与ip对应关系以及获取控制策略
  online:
    host: 192.168.0.174
    port: 16380
    password: "srun_3000@redis"
  # 4k cache, 在线表同步接口，用于接收用户上下线事件来同步dpi的在线表
  cache:
    host: 192.168.0.174
    port: 16384
    password: "srun_3000@redis"
